[project]
name = 'Technotelepathy-Research-Platform'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.neural-interface]
path = 'contracts/neural-interface.clar'
clarity_version = 2
epoch = 2.5

[contracts.technotelepathy-token]
path = 'contracts/technotelepathy-token.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
